#message
echo -e "Start coding bro 😤\nStop wasting time 😑\nBuild something today 💻\nDebugging is your destiny 😂" | shuf -n1 | cowsay -f tux | lolcat


# Font
font_family JetBrainsMono Nerd Font
font_size 12

# Cursor
cursor_shape block
cursor_blink_interval 0

# Window
window_padding_width 10
background_opacity 0.95

# Scrollback
scrollback_lines 10000

# Colors (simple dark theme)
foreground #cdd6f4
background #000000

# Selection
selection_foreground #1e1e2e
selection_background #f5e0dc

# Tabs
tab_bar_edge top
tab_bar_style fade
tab_title_template "{title}"

# Enable ligatures
enable_ligatures yes